package com.fastcash.speedloancoach.quickloan.mukesh_pkg_eight;

public enum mukesh_four_ghima {
    PERSONAL_LOAN("Personal Loan", "Personal loans can be used for any personal expenses and don’t have a designated purpose. This makes them an attractive option for people with outstanding debts, such as credit card debt, who want to reduce their interest rates by transferring balances. Like other loans, personal loan terms depend on your credit history.\\nA personal loan is an amount of money you can borrow to use for a variety of purposes. For instance, you may use a personal loan to consolidate debt, pay for home renovations, or plan a dream wedding. Personal loans can be offered by banks, credit unions, or online lenders. The money you borrow must be repaid over time, typically with interest. Some lenders may also charge fees for personal loans.\nA personal loan is also different from a personal line of credit. The latter is not a lump sum amount; instead, it works like a credit card. You have a credit line that you can spend money against and, as you do so, your available credit is reduced. You can then free up available credit by making a payment toward your credit line."),
    AUTO_LOAN("Auto Loan", "Like mortgages, auto loans are tied to your property. They can help you afford a vehicle, but you risk losing the car if you miss payments. This type of loan may be distributed by a bank or by the car dealership directly but you should understand that while loans from the dealership may be more convenient, they often carry higher interest rates and ultimately cost more overall.\nAn Auto Loan is taken by borrowers to purchase a new or used private or commercial vehicle. Auto loans are secured loans where the vehicle itself is used as a collateral. It is offered by lenders for new cars, used cars, two wheelers (generally called a Two-wheeler Loan) and commercial vehicles (generally called a Commercial Vehicle Loan).\n Lenders fix interest rates depending on the type of vehicle and loan amount. Interest rates are usually fixed for auto loans.\nIt is not always necessary to go with the bank your vehicle dealer suggests, you can always go to another lender if they offer better loan terms. Therefore, always do a thorough research by comparing lenders and their rates before finalizing a lender."),
    HOME_LOAN("Home Loan", "If you have equity in your home – the house is worth more than you owe on it – you can use that equity to help pay for big projects. Home equity loans are good for renovating the house, consolidating credit card debt, paying off student loans and many other worthwhile projects.\nhis is the most common type of home loan availed to purchase a house. There are many housing finance companies, public banks, and private banks that offer housing loans where you borrow money to purchase the house of your choice and repay the loan in monthly instalments.You can get up to 80%-90% of the houses market price in the form of financing. The lender will hold the house until you completely repay the loan.This is the right home loan type if you already have a plot of land and you need financing to construct a house in that land. \nA home improvement loan provides financing for renovating or repairing the house if there’s any fault in the existing system, such as painting the house’s interior or exterior, plumbing, upgrading the electrical system, waterproofing the ceiling, and more."),
    BUSINESS_LOAN("Business Loan", "To promote small enterprises in the country, the government has introduced several loan schemes. Apart from the Pradhan Mantri Mudra Yojana, there are many other schemes in which you can take small loans to big loans.1010 At this time, according to the schemes of the central and state government, you can take a loan of Rs 50,000 to Rs 1 lakh for your business.1010 Actually banks decide to give you a loan according to your business plan. If the bank feels that your business and profits from it will be so much that you will be able to repay the loan of the bank within the stipulated period after completing your expenses, only then the bank approves your loan.1010 What are the benefits of taking a business loan? Financial support for inward business needs of cash to meet financial needs for both short and long term.\n A bank loan may be obtained from a bank and may be either secured or unsecured. For secured loans, banks will require collateral, which may be lost if repayments are not made. The bank will probably wish to see the business’s accounts, balance sheet and business plan, as well as studying the principals' credit histories. Many smaller businesses are now however turning towards Alternative Finance Providers, especially in the case of smaller firms."),
    STUDENT_LOAN("Student Loan", "Student loans are offered to college students and their families to help cover the cost of higher education. There are two main types: federal student loans and private student loans. Federally funded loans are better, as they typically come with lower interest rates and more borrower-friendly repayment terms.\n An education loan is a sum of money borrowed to finance post-secondary education or higher education-related expenses. Education loans are intended to cover the cost of tuition, books and supplies, and living expenses while the borrower is in the process of pursuing a degree. Payments are often deferred while students are in college and, depending on the lender, sometimes they are deferred for an additional six-month period after earning a degree. This period is sometimes referred to as a \"grace period.\"Education loans are issued for the purpose of attending an accredited college or a university and pursuing an academic degree. Education loans can be obtained from the government or through private-sector lending sources.Federal loans often offer lower interest rates, and some also offer subsidized interest. Private-sector loans generally follow more of a traditional lending process for application, with rates that are typically higher than federal government loans."),
    MORTGAGES("Mortgages", "Mortgages are loans distributed by banks to allow consumers to buy homes they can’t pay for upfront. A mortgage is tied to your home, meaning you risk foreclosure if you fall behind on payments. Mortgages have among the lowest interest rates of all loans.\n Mortgage refers to the process of offering something as a guarantee or collateral against a loan. One may come across the term when looking for secured loans.Generally, home loans of all types are secured loans. The borrower must offer their property as a security to the lender. The property mortgaged acts as collateral until the borrower has repaid the loan in full. Mortgage loans are also commonly known as loans against property.A mortgage loan can be used to either buy or build a house or refinance a property. Refinancing refers to getting a new loan for a property while the original loan is still being repaid. It is usually done to get a loan with better terms.A simple mortgage is an agreement that if the borrower is unable to repay the loan in full, the lender can sell the property that was offered as collateral and recover their amount. However, the property is not transferred to the lender.The collateral can come under the possession of the lender if the borrower fails to make full repayment of the loan during the tenure originally agreed upon."),
    PAYDAY_LOAN("Payday Loan", "Payday loans are short-term, high-interest loans designed to bridge the gap from one paycheck to the next, used predominantly by repeat borrowers living paycheck to paycheck. The government strongly discourages consumers from taking out payday loans because of their high costs and interest rates.\n A payday loan is a type of short-term borrowing where a lender will extend high-interest credit based on your income. Its principal is typically a portion of your next paycheck. Payday loans charge high interest rates for short-term immediate credit. They are also called cash advance loans or check advance loans.Payday loan providers will normally require you to show proof of your income—usually your pay stubs from your employer. They will then lend you a portion of the money that you will be paid. You will have to pay the loan back within a short time, generally 30 days or less.Payday lenders take on a lot of risk, because they don’t check your ability to pay back the loan. Because of this, they normally charge very high interest rates for payday loans, and they may also charge high fees if you miss your repayments. This can be dangerous for borrowers, because it can mean that you’ll need to borrow more money to cover the cost of the first loan.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders."),
    SMALL_BUSINESS("Small Business", "Everyone\\'s dream is to have a branded car with them at home. A car not only makes your life comfortable, but also reduces many difficulties. Reaching the office while battling public transport or going out for weekends, everything becomes very easy.1010 Earlier, buying a car was a big thing for anyone, because it had to spend a lump sum, but now it is very easy due to the easy availability of a car loan.1010 Banks and non-banking finance companies offer car loans on easy monthly installments, which has made it very easy to buy cars. Due to this, your budget is not deteriorated and convenience is also available.\n Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.");

    public String description;
    public String name;

    private mukesh_four_ghima(String str, String str2) {
        this.name = str;
        this.description = str2;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }

    public String toString() {
        return this.name;
    }
}
